<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marie Rivers">
<meta name="dcterms.date" content="2021-12-02">
<meta name="description" content="Population Change vs.&nbsp;the EPA Environmental Quality Index (EQI): a statistical analysis">

<title>Marie T. Rivers - Does Environmental Quality Influence Where People Live?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../<i class=&quot;fa-solid fa-star&quot;></i>" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Marie T. Rivers</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../code_samples.html">
 <span class="menu-text">Code Samples</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html">
 <span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume/rivers_marie_resume.pdf">
 <span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/marierivers"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Does Environmental Quality Influence Where People Live?</h1>
                  <div>
        <div class="description">
          Population Change vs.&nbsp;the EPA Environmental Quality Index (EQI): a statistical analysis
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">R</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Marie Rivers </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 2, 2021</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  </ul></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a>
  <ul class="collapse">
  <li><a href="#environmental-quality-index" id="toc-environmental-quality-index" class="nav-link" data-scroll-target="#environmental-quality-index">Environmental Quality Index</a></li>
  <li><a href="#census-population-data" id="toc-census-population-data" class="nav-link" data-scroll-target="#census-population-data">Census Population Data</a></li>
  </ul></li>
  <li><a href="#statistical-analysis" id="toc-statistical-analysis" class="nav-link" data-scroll-target="#statistical-analysis">Statistical Analysis</a>
  <ul class="collapse">
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a></li>
  <li><a href="#domain-specific-linear-models" id="toc-domain-specific-linear-models" class="nav-link" data-scroll-target="#domain-specific-linear-models">Domain Specific Linear Models</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p><strong>This post discusses a statistical analysis used to answer the question: Does environmental quality influence where people live in the United States?</strong></p>
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>The Environmental Quality Index (EQI), developed by the U.S. Environmental Protection Agency (EPA) provides a county level snapshop of environmental conditions throughout the country. EPA first released EQIs for the period 2000-2005 and updated these indexes for 2006-2010. This statistical evaluation focuses on the 2006-2010 EQI. The purpose of the EQI is to use (1) as an indicator of ambient conditions/exposure in environmental health and modeling and (2) as a covariate to adjust for ambient conditions in environmental models (EPA 2020). Previous studies have used the EQI to evaluate relationships between environmental quality and public health outcomes such as cancer incidence, asthma, obesity, and infant mortality.</p>
<p>The EQI is developed from five domains each with identified environmental constructs as shown in Table 1. Each county has an overall environmental index and a domain specific index. Indexes were also stratified by rural-urban continuum codes (RUCCs) for counties classified as metropolitan urbanized, non-metro urbanized, less urbanized, and thinly populated.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<caption>EQI Environmental Domains and Constructs</caption>
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> Domain </th>
   <th style="text-align:left;font-weight: bold;"> Constructs </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;"> air </td>
   <td style="text-align:left;"> criteria air pollutants and hazardous air pollutants </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;"> water </td>
   <td style="text-align:left;"> overall water quality, general water contamination, domestic use, atmospheric deposition, drought, chemical contamination, and drinking water quality </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;"> land </td>
   <td style="text-align:left;"> agriculture, pesticides, facilities, radon, and mining activity </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;"> built </td>
   <td style="text-align:left;"> roads, highway/road safety, commuting behavior, housing environment, walkability, and green space </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;border-right:1px solid;"> sociodemographic </td>
   <td style="text-align:left;"> crime, socioeconomic, political character, and creative class representation </td>
  </tr>
</tbody>
</table>

</div>
</div>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p>While the EQI can identify counties with higher environmental burdens, it may not identify environmental injustices at the local community level. The EQI cannot quantify environmental exposure for individuals and reflects only outside environmental conditions, not indoor conditions. The EQI can be used to identify locations for future research, but is not intended for regulatory purposes or as a diagnostics tool. Due to changes in methodology and datasets, the 2000-2005 and 2006-2010 EQIs should not be directly compared.</p>
</section>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<section id="environmental-quality-index" class="level3">
<h3 class="anchored" data-anchor-id="environmental-quality-index">Environmental Quality Index</h3>
<p>To develop the EQI, variables were identified from available data to represent each environmental domain and assessed for collinearity so redundant variables could be excluded. Variables were standardized based on geographic space or on a per capita rate, as appropriate and transformations such as log-transformations were performed as needed based on the normality of each variable. Data gaps were evaluated to distinguish between missing data and meaningful zeros. Where applicable, spatial kriging was used to interpolate values when data was not available for all counties. Principal component analysis was used to aggregate variables into domain specific indexes. The domain indexes were then aggregated into overall indexes for each county. A result of this method is that each domain does not equally influence the overall EQI value for a given county. The EQI is developed to be normally distributed with mean=0 and standard deviation=1. <strong>Higher EQI values correspond with worse environmental quality. Lower (more negative) EQI values correspond with better environmental quality.</strong></p>
</section>
<section id="census-population-data" class="level3">
<h3 class="anchored" data-anchor-id="census-population-data">Census Population Data</h3>
<p>County level population data was obtained from the U.S. Census Bureau’s county intercensal datasets for 2000-2010. Percent population change was calculated for 2006-2010 then winsorized to remove outliers above the 99.9th percentile (ie. counties with population change above 28.5%).</p>
</section>
</section>
<section id="statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis">Statistical Analysis</h2>
<p>Kalawao County, Hawaii had the lowest EQI value (highest environmental quality) and greatest decrease in population (-17.4%). Falls Church, Virginia had the highest EQI (lowest environmental quality) and a population change of 15.4% which falls is the 99th percentile. The summary statistics in Table 2 suggest that population growth is correlated with worse environmental characteristics.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<caption>EQI summary statistics for counties based on population change between 2006 and 2010</caption>
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> Population Change </th>
   <th style="text-align:right;font-weight: bold;"> Min </th>
   <th style="text-align:right;font-weight: bold;"> Max </th>
   <th style="text-align:right;font-weight: bold;"> Mean </th>
   <th style="text-align:right;font-weight: bold;"> Standard Deviation </th>
   <th style="text-align:right;font-weight: bold;"> Variance </th>
   <th style="text-align:right;font-weight: bold;"> Number of Counties </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> negative </td>
   <td style="text-align:right;"> -5.88 </td>
   <td style="text-align:right;"> 2.59 </td>
   <td style="text-align:right;"> -0.24 </td>
   <td style="text-align:right;"> 0.93 </td>
   <td style="text-align:right;"> 0.87 </td>
   <td style="text-align:right;"> 1088 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> positive </td>
   <td style="text-align:right;"> -5.05 </td>
   <td style="text-align:right;"> 2.85 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 1.01 </td>
   <td style="text-align:right;"> 1.02 </td>
   <td style="text-align:right;"> 2052 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;background-color: #e5e5e5 !important;"> all counties </td>
   <td style="text-align:right;font-weight: bold;background-color: #e5e5e5 !important;"> -5.88 </td>
   <td style="text-align:right;font-weight: bold;background-color: #e5e5e5 !important;"> 2.85 </td>
   <td style="text-align:right;font-weight: bold;background-color: #e5e5e5 !important;"> 0.00 </td>
   <td style="text-align:right;font-weight: bold;background-color: #e5e5e5 !important;"> 1.00 </td>
   <td style="text-align:right;font-weight: bold;background-color: #e5e5e5 !important;"> 1.00 </td>
   <td style="text-align:right;font-weight: bold;background-color: #e5e5e5 !important;"> 3140 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<section id="hypothesis-testing" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h3>
<p>A different means test was completed to determine if mean environmental quality was statistically different for counties that experienced positive vs.&nbsp;negative population change between 2006-2010. The figure below shows a histogram of EQI values for counties with negative and positive population change.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>null hypothesis:</strong> There is no difference in mean EQI for counties with positive and negative population change.</p>
<p><span class="math display">\[H_{0}: \mu_{posPopChange} - \mu_{negPopChange} = 0\]</span></p>
<p><strong>alternative hypothesis:</strong> There is a difference in mean EQI for counties with positive and negative population change.</p>
<p><span class="math display">\[H_{A}: \mu_{posPopChange} - \mu_{negPopChange} \neq 0\]</span></p>
<div class="cell">

</div>
<div class="cell">

</div>
<p><span class="math display">\[\text{point estimate} = \mu_{posPopChange} - \mu_{negPopChange} =0.131 - -0.245 = 0.376\]</span></p>
<p>The standard error for the difference in means is:</p>
<p><span class="math display">\[SE = \sqrt{\frac{s_1^2}{n_1} + \frac{s^2_2}{n_2}} = \sqrt{\frac{1.009^2}{2052} + \frac{0.933^2}{1088}} = 0.036\]</span></p>
<p>The z-score for hypothesis testing is:</p>
<p><span class="math display">\[z = \frac{\text{point estimate - null}}{SE} = \frac{0.376 - 0}{0.036} = 10.443\]</span></p>
<div class="cell">

</div>
<p>The p-value, the probability of getting a point estimate at least as extreme as calculated if the null hypothesis were true, is:</p>
<p><span class="math display">\[p\text {-value }=\operatorname{Pr}(Z&lt;-|z| \text { or } Z&gt;|z|)=2 * \operatorname{Pr}(Z&gt;|z|) = 1.5809578\times 10^{-25}\]</span></p>
<div class="cell">

</div>
<p>Since the p-value is &lt; 0.001 we reject the null that there is no difference in EQI for counties with positive population change versus negative population change. There is a statistically significant difference (at the 0.1% significance level) in EQI across the two population change groups. The 95% confidence interval ranges from 0.31 to 0.45. This means that there is a 95% chance that this interval includes the true difference in mean EQI between counties with positive and negative percent population change.</p>
</section>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">Linear Regression</h3>
<p>Linear regression was used to model the relationship between population change and environmental quality using the overall EQI value and each domain specific EQI to determine if a particular domain was a stronger predictor of population change.</p>
<p><span class="math display">\[\text{percent population change}_i=\beta_{0}+\beta_{1} \cdot EQI_i + \varepsilon_i\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>First, hypothesis testing was used to test whether the slope coefficient for the percent population change rate is equal to zero or not.</p>
<p><strong>null hypothesis:</strong> The slope coefficient is equal to zero</p>
<p><span class="math display">\[H_{0}: \beta_{1} = 0\]</span> <strong>alternative hypothesis:</strong> The slope coefficient is <strong>NOT</strong> equal to zero</p>
<p><span class="math display">\[H_{A}: \beta_{1} \neq 0\]</span> ::: {.cell}</p>
<p>:::</p>
<p>The point estimate, <span class="math inline">\(\beta_1\)</span> = 0.991 and the standard error, SE = 0.077.</p>
<p><span class="math display">\[z = \frac{\text{point estimate - null}}{SE} = \frac{{0.991 - 0}}{0.077} = 12.817\]</span></p>
<p><span class="math display">\[p\text {-value }=\operatorname{Pr}(Z&lt;-|z| \text { or } Z&gt;|z|)=2 * \operatorname{Pr}(Z&gt;|z|) = 1.0849376\times 10^{-36}\]</span></p>
<div class="cell">

</div>
<p>Since the p-value for the slope coefficient was &lt; 0.001, we reject the null hypothesis that EQI has no influence on population change at the 0.1% level. There is a statistically significant relationship between EQI and percent population change and the coefficient is significantly different from zero. Based on value of <span class="math inline">\(\beta_1\)</span>, for each one unit increase in EQI, the percent population change increases by 0.991. The 95% confidence interval for the slope coefficient ranges from 0.84 to 1.143. This means that there is a 95% chance that this interval includes the true county level rate of change for percent population change for each one unit change in EQI.</p>
</section>
<section id="domain-specific-linear-models" class="level3">
<h3 class="anchored" data-anchor-id="domain-specific-linear-models">Domain Specific Linear Models</h3>
<p><span class="math display">\[\text{percent population change}_i=\beta_{0,domain}+\beta_{1,domain} \cdot EQI_{i,domain} + \varepsilon_i\]</span> ::: {.cell}</p>
<p>:::</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>While a partly manual method was used above, statistical functions in R were used to test for the significance of domain models. Table 3 presents coefficients for each domain specific model. The numbers in [brackets] are the 95% confidence intervals for each estimated coefficient.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-paper table" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<caption>Summary of EQI Domain Slope Coefficients</caption>
 <thead>
  <tr>
   <th style="text-align:left;font-weight: bold;"> coefficient </th>
   <th style="text-align:left;font-weight: bold;"> overall EQI </th>
   <th style="text-align:left;font-weight: bold;"> air model </th>
   <th style="text-align:left;font-weight: bold;"> water model </th>
   <th style="text-align:left;font-weight: bold;"> land model </th>
   <th style="text-align:left;font-weight: bold;"> built model </th>
   <th style="text-align:left;font-weight: bold;"> sociodem model </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;"> Intercept </td>
   <td style="text-align:left;font-weight: bold;"> 1.868 *** </td>
   <td style="text-align:left;font-weight: bold;"> 1.869 *** </td>
   <td style="text-align:left;font-weight: bold;"> 1.868 *** </td>
   <td style="text-align:left;font-weight: bold;"> 1.868 *** </td>
   <td style="text-align:left;font-weight: bold;"> 1.867 *** </td>
   <td style="text-align:left;font-weight: bold;"> 1.868 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;"> [1.716, 2.019] </td>
   <td style="text-align:left;"> [1.717, 2.020] </td>
   <td style="text-align:left;"> [1.714, 2.023] </td>
   <td style="text-align:left;"> [1.713, 2.024] </td>
   <td style="text-align:left;"> [1.713, 2.021] </td>
   <td style="text-align:left;"> [1.718, 2.019] </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;"> EQI </td>
   <td style="text-align:left;font-weight: bold;"> 0.991 *** </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;"> [0.840, 1.143] </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;"> air EQI </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;"> 0.998 *** </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> [0.847, 1.150] </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;"> water EQI </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;"> 0.485 *** </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> [0.331, 0.640] </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;"> land EQI </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;"> -0.314 *** </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> [-0.469, -0.158] </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;"> built EQI </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;"> 0.635 *** </td>
   <td style="text-align:left;font-weight: bold;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> [0.481, 0.790] </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;"> sociodem EQI </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;font-weight: bold;"> 1.068 *** </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> [0.917, 1.219] </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> n </td>
   <td style="text-align:left;"> 3140 </td>
   <td style="text-align:left;"> 3140 </td>
   <td style="text-align:left;"> 3140 </td>
   <td style="text-align:left;"> 3140 </td>
   <td style="text-align:left;"> 3140 </td>
   <td style="text-align:left;"> 3140 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> R2 </td>
   <td style="text-align:left;"> 0.050 </td>
   <td style="text-align:left;"> 0.051 </td>
   <td style="text-align:left;"> 0.012 </td>
   <td style="text-align:left;"> 0.005 </td>
   <td style="text-align:left;"> 0.020 </td>
   <td style="text-align:left;"> 0.058 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The figure below provides a visual comparison of each model result. The bold portion of the line represents the 90% confidence interval and the full line represents the 95% confidence interval for each estimate.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The p-value on the slope coefficient was &lt; 0.001 for all domain specific linear models which indicates a statistically significant relationship at the 0.01% level. Based on the <span class="math inline">\(R^2\)</span> values and slope coefficients, the air and sociodemographic domains account for most of the overall relationship between population change and EQI. All domains except land are positively correlated with population change. Since higher EQI values indicate poorer environmental quality, these models show that population increased more in counties with worse environmental conditions. For a one unit increase in sociodemogrpahic EQI, the percent population change increases by 1.068. For a one unit increase in air EQI, the percent population change increases by 0.998. The <span class="math inline">\(R^2\)</span> terms represent the variance in percent population change that can be explained by EQI. For the overall EQI value, 5% of the variance in percent population change is explained by environmental conditions. The sociodemographic EQI explains 5.8% of the variance in population change while the air EQI explains 5.1%.</p>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>The identified relationships between population change and environmental quality are noteworthy for their public health and environmental justice implications. Positive population trends in areas with worse environmental conditions could result in increased incidences of cancer, asthma, obesity, and infant mortality. While this project did not evaluate economic variables, locations with higher environmental quality could also have higher living costs which drive people to move to more affordable places. If economic factors contribute to population growth in counties with poor environmental quality, then this could negatively affect the health of vulnerable populations and perpetuate social inequalities. Further analysis could evaluate trends in mean household income to determine if there is growing income inequality between counties with better and worse environmental quality. Economic variables and other factors influencing demographic shifts from rural areas to cities may be stronger predictors of population change than environmental quality.</p>
<p><strong>Data availability:</strong><br>
<a href="https://edg.epa.gov/data/public/ORD/CPHEA/">EPA Datasets and files from the EQI county data from 2006-2010</a><br>
<a href="https://www.census.gov/data/tables/time-series/demo/popest/intercensal-2000-2010-counties.html">U.S. Census Bureau County Intercensal Tables: 2000-2010</a></p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li><p>U.S. EPA. Environmental Quality Index - Technical Report (2006-2010) (Final, 2020). U.S. Environmental Protection Agency, Washington, DC, EPA/600/R-20/367, 2020.</p></li>
<li><p>U.S. Census Bureau. County Intercensal Datasets: 2000-2010. https://www.census.gov/data/datasets/time-series/demo/popest/intercensal-2000-2010-counties.html</p></li>
</ol>


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{rivers2021,
  author = {Marie Rivers},
  title = {Does {Environmental} {Quality} {Influence} {Where} {People}
    {Live?}},
  date = {2021-12-02},
  url = {https://marierivers.github.io/posts/2021-12-02-environmental-quality-population-change/},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-rivers2021" class="csl-entry quarto-appendix-citeas" role="doc-biblioentry">
Marie Rivers. 2021. <span>“Does Environmental Quality Influence Where
People Live?”</span> December 2, 2021. <a href="https://marierivers.github.io/posts/2021-12-02-environmental-quality-population-change/">https://marierivers.github.io/posts/2021-12-02-environmental-quality-population-change/</a>.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>