project:
  type: website
  output-dir: docs

website:
  title: "Marie Rivers"
  navbar:
    background: primary
    # left:
    right:
      - href: index.qmd
        text: Home
      # - href: code_samples.qmd
      #   text: Code Samples
      - code_samples.qmd
      - posts.qmd
      - href: data/rivers_marie_resume.pdf
        text: Resume
      - icon: github
        href: https://github.com/marierivers
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



