project:
  type: website
  output-dir: docs

website:
  title: "Marie T. Rivers"
  favicon: <i class="fa-solid fa-star"></i>
  navbar:
    background: primary
    # left:
    right:
      - href: index.qmd
        text: Home
      # - href: code_samples.qmd
      #   text: Code Samples
      - code_samples.qmd
      - posts.qmd
      - href: resume/rivers_marie_resume.pdf
        text: Resume
      - icon: github
        href: https://github.com/marierivers
        aria-label: GitHub

format:
  html:
    # theme: cosmo
    theme: 
      - simple_theme.scss
    css: styles.css
    toc: true



