---
title: "Bio"
description: |
  Marie Rivers, P.E.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Marie, a current environmental data science graduate student at UC Santa Barbara’s Bren School of Environmental Science and Management, holds Bachelors and Masters degrees in environmental engineering from the University of Delaware (2009) and University of Massachusetts (2011). She is also a registered professional civil water resources engineer with 10 years of consultant experience modeling and designing municipal drinking water distribution systems. During this time, she observed the growing need for reproducible data science and visualization skills to develop innovated solutions to current and emerging environmental problems. Marie grew up on a small New England lake with high water quality in part due to a mostly forested watershed. Throughout Marie’s academic and professional career, she gained a greater understanding of the factors that contribute to water quality. An initial interest in lake ecosystems expanded to a larger awareness of the interconnectedness of environmental conditions and public health. After graduation, Marie plans to use her degrees to evaluate interactions between human and natural systems and support implementation of measures that protect and improve the environment by communicating these dynamics to wider audiences.
